# Generated by Django 3.2 on 2021-06-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ManyToManyField(to='products.Category'),
        ),
        migrations.RemoveField(
            model_name='service',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='service',
            name='subcategory',
            field=models.ManyToManyField(to='products.Subcategory'),
        ),
    ]
