# Generated by Django 3.2 on 2021-06-07 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_service_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='plan_price',
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.RemoveField(
            model_name='service',
            name='plan',
        ),
        migrations.AddField(
            model_name='service',
            name='plan',
            field=models.ManyToManyField(to='products.Plan'),
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.plan')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.service')),
            ],
            options={
                'db_table': 'plan_price',
            },
        ),
    ]
