# Generated by Django 3.2 on 2021-06-07 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210607_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='planprice',
            name='id',
            field=models.BigAutoField(auto_created=True, default=23, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planprice',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.service'),
        ),
    ]
