# Generated by Django 3.2 on 2021-06-07 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210607_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planprice',
            name='id',
        ),
        migrations.AlterField(
            model_name='planprice',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.service'),
        ),
    ]
