# Generated by Django 3.2 on 2021-06-07 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210607_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planprice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.service'),
        ),
        migrations.AlterUniqueTogether(
            name='planprice',
            unique_together={('service', 'price')},
        ),
    ]
