# Generated by Django 3.2 on 2021-06-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210607_2245'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planprice',
            unique_together={('service', 'plan')},
        ),
    ]
