# Generated by Django 3.2 on 2021-06-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_planprice_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planprice',
            unique_together=set(),
        ),
    ]
