# Generated by Django 3.2 on 2021-06-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_planprice_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planprice',
            unique_together={('service', 'plan')},
        ),
    ]
