# Generated by Django 3.2 on 2021-06-11 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_planprice_unique_together'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='planprice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.planprice'),
            preserve_default=False,
        ),
    ]
