# Generated by Django 3.2 on 2021-06-12 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0013_alter_planprice_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateField(auto_now=True)),
                ('orderstatus', models.CharField(default='Processing', max_length=30)),
                ('totalbill', models.IntegerField()),
                ('ship_first_name', models.CharField(max_length=30)),
                ('ship_last_name', models.CharField(max_length=30)),
                ('ship_email', models.EmailField(max_length=254)),
                ('ship_contact', models.CharField(max_length=13)),
                ('ship_country', models.CharField(max_length=30)),
                ('ship_state', models.CharField(max_length=30)),
                ('ship_address', models.TextField(max_length=300)),
                ('ship_pin', models.IntegerField()),
                ('payment', models.CharField(max_length=30)),
                ('planprice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.planprice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
